# Generated by Django 4.1.2 on 2024-06-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_produit_options_alter_commande_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(blank=True, default=10, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='shop.category'),
        ),
    ]
